### ISSUE TITLE
Script cleanup

### ISSUE THREAD

**Issue by StackKorora** [TesterTech/OpenQA-Fedora-Installation#1]
Thank you so much for the videos and scripts. I'm just learning OpenQA and your work has been a big help. A few things about the scripts.
install-openqa-post.sh
* line 13 `sudo chown geekotest *` there's nothing in the directory as it was just created on line 10 `sudo mkdir -p /var/lib/openqa/factory/hdd/fixed` and then it cd's into that directory. Because there's nothing there, the script throws an error.
* line17 `sudo systemctl start openqa-worker@1` might be better to do `sudo systemctl enable --now openqa-worker@1` so that the service is enabled on boot and starts now.

install-openqa.sh
* Similar to above. There are a bunch of services that are enabled and started. eg: `sudo systemctl start sshd` then `sudo systemctl enable sshd` but all of these can be done with `sudo systemctl enable --now sshd`

Thanks again! I'm excited to see where your videos continue to go.

**Comment by endegraaf** [comment]
Thanks! Will look at these script improvements.

**Comment by endegraaf** [comment]
Have added these changes to the script, thanks again :-)
